//app.js
import wx from './wxsys/lib/base/wx';
import {initenv} from './wxsys/lib/base/initenv';
 wx.App = {baseUrl: 'https://fenxiang-app.newdaoapp.cn', resPath: 'https://fenxiang-app.newdaoapp.cn/mainapp'};
initenv();
new wx.ShareData({"name":"共享数据0","className":"/uaa/users","type":"rest-data"});

App({
  onLaunch: function () {
    // 云开发初始化
    wx.cloud.init({
      env: "go-w1pgy",
      traceUser: true,
    })
  },
  globalData: {
    BaseData:[{
      "id": 786,
      "sex": 0,
      "avatar": 1,
      "content": "玲玲刚刚成功参加抢购",
      "zanNumber": 31
    }, {
      "id": 787,
      "sex": 1,
      "avatar": 2,
      "content": "许俊庆刚刚成功参加抢购",
      "zanNumber": 30
    }, {
      "id": 788,
      "sex": 1,
      "avatar": 3,
      "content": "顺其自然刚刚成功参加抢购",
      "zanNumber": 43
    }, {
      "id": 789,
      "sex": 0,
      "avatar": 4,
      "content": "丽丽刚刚成功参加抢购",
      "zanNumber": 50
    }, {
      "id": 790,
      "sex": 0,
      "avatar": 5,
      "content": "幸福就好刚刚成功参加抢购",
      "zanNumber": 62
    }, {
      "id": 791,
      "sex": 0,
      "avatar": 6,
      "content": "向阳花刚刚成功参加抢购",
      "zanNumber": 1
    }, {
      "id": 792,
      "sex": 1,
      "avatar": 7,
      "content": "笑看人生刚刚成功参加抢购",
      "zanNumber": 2
    }, {
      "id": 793,
      "sex": 0,
      "avatar": 8,
      "content": "张丽丽刚刚成功参加抢购",
      "zanNumber": 8
    }, {
      "id": 794,
      "avatar": 9,
      "sex": 0,
      "content": "王月刚刚成功参加抢购",
      "zanNumber": 9
    }, {
      "id": 795,
      "avatar": 10,
      "sex": 0,
      "content": "李莉刚刚成功参加抢购",
      "zanNumber": 75
    }, {
      "id": 796,
      "avatar": 11,
      "sex": 0,
      "content": "莲花刚刚成功参加抢购",
      "zanNumber": 63
    }, {
      "id": 797,
      "avatar": 12,
      "sex": 1,
      "content": "明珠刚刚成功参加抢购",
      "zanNumber": 7
    }, {
      "id": 798,
      "avatar": 13,
      "sex": 0,
      "content": "慧萍刚刚成功参加抢购",
      "zanNumber": 3
    }, {
      "id": 799,
      "avatar": 14,
      "sex": 0,
      "content": "雨雪刚刚成功参加抢购",
      "zanNumber": 0
    }, {
      "id": 800,
      "avatar": 15,
      "sex": 1,
      "content": "张倩刚刚成功参加抢购",
      "zanNumber": 80
    }, {
      "id": 801,
      "avatar": 16,
      "sex": 1,
      "content": "杨平刚刚成功参加抢购",
      "zanNumber": 41
    }, {
      "id": 802,
      "avatar": 17,
      "sex": 1,
      "content": "皮皮刚刚成功参加抢购",
      "zanNumber": 22
    }, {
      "id": 803,
      "avatar": 18,
      "sex": 0,
      "content": "甜甜刚刚成功参加抢购",
      "zanNumber": 86
    }, {
      "id": 804,
      "avatar": 19,
      "sex": 1,
      "content": "小武刚刚成功参加抢购",
      "zanNumber": 63
    }, {
      "id": 805,
      "avatar": 20,
      "sex": 0,
      "content": "王保娟刚刚成功参加抢购",
      "zanNumber": 12
    }, {
      "id": 806,
      "avatar": 21,
      "sex": 1,
      "content": "多多刚刚成功参加抢购",
      "zanNumber": 4
    }, {
      "id": 807,
      "avatar": 22,
      "sex": 0,
      "content": "点点刚刚成功参加抢购",
      "zanNumber": 13
    }, {
      "id": 808,
      "avatar": 23,
      "sex": 1,
      "content": "孙晨刚刚成功参加抢购",
      "zanNumber": 8
    }, {
      "id": 809,
      "avatar": 24,
      "sex": 1,
      "content": "冰雪刚刚成功参加抢购",
      "zanNumber": 1
    }, {
      "id": 810,
      "avatar": 25,
      "sex": 0,
      "content": "雪玲刚刚成功参加抢购",
      "zanNumber": 0
    }, {
      "id": 811,
      "avatar": 26,
      "sex": 0,
      "content": "小葡萄刚刚成功参加抢购",
      "zanNumber": 7
    }, {
      "id": 812,
      "avatar": 27,
      "sex": 1,
      "content": "梦想成真刚刚成功参加抢购",
      "zanNumber": 5
    }, {
      "id": 813,
      "avatar": 28,
      "sex": 0,
      "content": "阿茹刚刚成功参加抢购",
      "zanNumber": 4
    }, {
      "id": 814,
      "avatar": 29,
      "sex": 0,
      "content": "雪儿刚刚成功参加抢购",
      "zanNumber": 3
    }],
    IconGood: '/images/index/icon-good.png',
    IconBoy: '/images/index/icon-boy.png',
    IconGirl: '/images/index/icon-girl.png',
    Banner: '/images/index/demo-banner.jpg',
  }
})